@isTest
public class Test_TStringUtils {

    @isTest
    public static void TStringUtilsMethod() {
        
        Test.startTest();
        /*
        TStringUtils ct = new TStringUtils();
        ct.GetDependentOptions(String pObjName('Test Object'), String pControllingFieldName('Test Controlling Field'), String pDependentFieldName('Test Dependent Field'));
        */
        Test.stopTest();
    }
}