public class Schedule_Lifepoints_CounterBatch
{
   /* public static String sched = '0 0 05 * * ?';  //Every Day at 05:00 o'clock 
 //For scheduling --> Schedule_Lifepoints_CounterBatch.scheduleMe();
    public static String scheduleMe() {
        Schedule_Lifepoints_CounterBatch SC = new Schedule_Lifepoints_CounterBatch();  
        return System.schedule('Batch LifepointsCounter', sched, SC); 
    }

    public void execute(SchedulableContext sc) {
        LifepointsCounter b1 = new LifepointsCounter ();
        ID batchprocessid = Database.executeBatch(b1,1);            
    }*/
}